name: Android Staging CI/CD Pipeline

on:
  push:
    branches:
      - develop  # Adjust if you use a different branch for staging
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging  # Specify the staging environment here

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download Dependencies
        run: ./gradlew build --no-daemon

      - name: Run Unit Tests
        run: ./gradlew test --no-daemon

      - name: Assemble Release APK
        run: ./gradlew assembleRelease

      - name: Upload to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > serviceAccount.json
          ./gradlew appDistributionUploadRelease -PfirebaseAppId=${{ secrets.FIREBASE_APP_ID }}
