name: Deploy to Firebase App Distribution

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Google Services JSON
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: List APK files
        run: |
          echo "Listing all APK files:"
          find . -name "*.apk"
          echo "Listing contents of build/outputs directory:"
          ls -R app/build/outputs/

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
          groups: "Staging Testers"
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: |
            Changes in this build:
            - Commit message: ${{ github.event.head_commit.message }}